default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: erictodasco
  host: localhost

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: your_production_user
  password: <%= ENV["DATABASE_PASSWORD"] %>
