default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: erictodasco
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: scheduled_tweets_development
  # Uncomment if you need a password:
  # password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: scheduled_tweets_test

production:
  <<: *default
  database: scheduled_tweets_production
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  # Uncomment if using a password:
  # password: <%= ENV['POSTGRES_PASSWORD'] %>
